apiVersion: v1
kind: DeploymentConfig
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
  triggers:
    -
      type: ConfigChange
  replicas: 1
  test: false
  selector:
    name: postfix
  template:
    metadata:
      labels:
        name: postfix
    spec:
      volumes:
        -
          name: shared-root
          emptyDir:
      containers:
        -
          name: postfix
          image: 'goern/postfix-centos7'
          ports:
            -
              name: smtp
              containerPort: 25
              protocol: TCP
          resources:
          volumeMounts:
            -
              name: shared-root
              mountPath: /srv/postfix
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
          securityContext:
        -
          name: rsyslog
          image: 'goern/rsyslog-centos7'
          resources:
          volumeMounts:
            -
              name: shared-root
              mountPath: /srv/postfix
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
          securityContext:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
